#Set this value to false unless explicitly told to change it by ZXSkelobrine
debug: false

#This is the message if the vote goes to a chance decider
chance: 'Letting the gods decide'

#These are the success messages
success:
  day: 'Vote is a success the time is set to day'
  night: 'Vote is a success the time is set to night'
  rain:
    start: 'Vote is a success the rain is starting'
    stop: 'Vote is a success the rain is stopping'

kick:
  kick1: 'Vote is a success '
  kick2: ' will be kicked'
  kickThreshold: 2
ban:
  ban1: 'Vote is a success '
  ban2: ' will be banned'
  banThreshold: 5

#This is how long the vote lasts for (In seconds - 300 = 5 minutes)
timer: 300